
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance Optimizations
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_new: true
    unnecessary_this: true
    
    # Code Cleanliness
    avoid_print: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_string_escapes: false